In [1]:
import torch
print(torch.__version__)

2.1.1+cpu


# Introduction to Tensors
Tensors are multi-dimensional arrays that generalize the concept of scalars, vectors and matrices. Tensors are a crucial concept in deep learning frameworks because they provide a flexible way to represent and manipulate data.

### 1. Scalar Tensors:
A 0-dimensional tensor. It represents a single numerical value.

In [2]:
# Scalar
scalar = torch.tensor(9)
print(scalar)
print(scalar.ndim)     # number of dimensions of a tensor
print(scalar.shape)


tensor(9)
0
torch.Size([])


### 2. Vector Tensors:
A 1-dimensional tensor. It is an array of numbers arranged along a single axis. Basically, a vector has magnitude and direction.

In [3]:
# Vector
vector = torch.tensor([2,5])
print(vector)
print(vector.ndim)
print(vector.shape)

tensor([2, 5])
1
torch.Size([2])


### 3. Matrix Tensors:
A 2-dimensional tensor. It is an array of numbers arranged in rows and columns.

In [4]:
# Matrix
MATRIX = torch.tensor([[4,3],
                       [2,5],
                       [7,8]])
print(MATRIX)
print(MATRIX.ndim)
print(MATRIX.shape)

tensor([[4, 3],
        [2, 5],
        [7, 8]])
2
torch.Size([3, 2])


In [5]:
print(MATRIX[1])
print(MATRIX[1].shape)

tensor([2, 5])
torch.Size([2])


### 4.  Tensors:
A general term for multi-dimensional arrays. Tensors can have any number of dimensions. <br>For example, a 3-dimensional tensor can be thought of as a cube of numbers.

In [6]:
# Tensors
TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]])
print(TENSOR)
print(TENSOR.ndim)
print(TENSOR.shape)

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
3
torch.Size([1, 3, 3])


<small> <i>torch.Size([1, 3, 3])</i> represents the size or shape of the tensor along each dimension.<br> In this case, it's a 3D tensor with a size of 1 along the first dimension and size 3 along the next two dimensions. So, the tensor is effectively a <i>1x3x3</i> tensor.</small>

<img src = 'https://raw.githubusercontent.com/mrdbourke/pytorch-deep-learning/main/images/00-pytorch-different-tensor-dimensions.png'>

In [7]:
# Extracting a 2D tensor from the original 3D tensor
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

Generally,
- Scalars are represented by lowercase variable names, e.g, `a`
- Vectors are also represented by lowercase variable names, e.g, `x`
- Matrices are represented by uppercase variable names, e.g, `A`
- Tensors are also represented by uppercase variable names, e.g, `X`


### Random Tensors
Random tensors play a crucial role in the learning process of neural networks. The typical sequence involves:

1. **Initialization**: Neural networks start with tensors filled with random numbers.
2. **Observation of Data**: The network processes and analyzes the available data.
3. **Parameter Update**: Adjustments are made to the initially random numbers based on the observed data.
4. **Iteration**: The process iterates, with the network continuously updating its parameters to better represent the underlying patterns in the data.

This iterative cycle of starting with randomness and refining through data-driven updates forms the foundation of how neural networks learn. 

<a href='https://pytorch.org/docs/stable/generated/torch.rand.html'>TORCH.RAND Documentation</a>

In [8]:
# Random Tensors
random_tensors = torch.rand(1,3,5)
random_tensors

tensor([[[0.4902, 0.8865, 0.8125, 0.2303, 0.1670],
         [0.8679, 0.2228, 0.7466, 0.0892, 0.8423],
         [0.4279, 0.8854, 0.9223, 0.4115, 0.1438]]])

In [9]:
random_tensors.ndim, random_tensors.shape

(3, torch.Size([1, 3, 5]))

In tensor-speak, the tensor would have three dimensions, one for [colour_channels, height, width] or [height, width, color_channels].

<img src='https://raw.githubusercontent.com/mrdbourke/pytorch-deep-learning/main/images/00-tensor-shape-example-of-image.png'>

In [10]:
# Create a random tensor with similar shape to an image tensor
random_image_tensor = torch.rand(size=(223,255,3))   # height, width, color_channels(R,G,B)
random_image_tensor.ndim, random_image_tensor.shape 

(3, torch.Size([223, 255, 3]))

### Zeros and Ones

In [11]:
# Create a tensor of all zeros
zeros = torch.zeros(3,3)
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [12]:
# Create a tensor of all ones
ones = torch.ones(3,3)
ones

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [13]:
# Type of zeros and ones tensors
zeros.dtype, ones.dtype

(torch.float32, torch.float32)

### Range of Tensors and Tensors-like
<a href='https://pytorch.org/docs/stable/generated/torch.arange.html'>TORCH.ARANGE Documentation</a>

In [14]:
# Creating a range of tensors
torch.arange(0,5)   # (start=0, end=5)

tensor([0, 1, 2, 3, 4])

In [15]:
range = torch.arange(0,1000,100)    # (start=0, end=10, step=2)
range

tensor([  0, 100, 200, 300, 400, 500, 600, 700, 800, 900])

In [16]:
# Creating a range of tensors-like
range_zeros = torch.zeros_like(range)
range_ones = torch.ones_like(range)
range_zeros, range_ones

(tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1]))