In [1]:
import torch

### Tensor DataTypes
**Note:**

Tensor DataTypes are critical considerations to avoid common errors in PyTorch and Deep Learning. <br>The 3 significant issues you may encounter are:

1. **Incorrect Data Types**: Ensure that tensors have the appropriate data types for your operations. <br> Most of the time different manipulation of tensor of different data types works.
    ```bash
    tensor.dtype
    ```

2. **Incorrect Shape**: Verify that tensors have the correct shape as required by your model and operations.
    ```bash
    tensor.shape
    ```

3. **Incorrect Device**: Tensors should be placed on the right device (CPU or GPU) for efficient computation.
    ```bash
    tensor.device
    ```

![Image](https://github.com/mrdbourke/pytorch-deep-learning/raw/main/images/misc-three-main-errors-in-pytorch.png)


In [7]:
# Float32 Tensor [Default], Device = cpu [Default]
float32_tensor = torch.tensor([3.0, 4.0, 5.0, 6.0],
                              dtype=None,   # What data type is the tensor [float32 or float16]
                              device=None,  # What device is your tensor on [cpu or cuda]
                              requires_grad=False)  # Whether or not to track gradients 
float32_tensor

tensor([3., 4., 5., 6.])

In [4]:
float32_tensor.dtype

torch.float32

In [5]:
# Change Float32 Tensor to Float16 Tensor
float16_tensor = float32_tensor.type(torch.float16)
float16_tensor

tensor([3., 4., 5., 6.], dtype=torch.float16)

In [ ]:
float16_tensor * float32_tensor

In [ ]:
# Manipulating int32 tensor with float32 tensor
int32_tensor = torch.tensor([3.0, 4.0, 5.0, 6.0], dtype = torch.int32)
int32_tensor

In [10]:
# Create a tensor
X = torch.rand(3,4)
X

tensor([[0.5890, 0.0688, 0.2010, 0.3729],
        [0.7517, 0.0447, 0.0649, 0.1547],
        [0.9262, 0.4714, 0.6713, 0.3562]])

In [16]:
print(f'Datatype of tensorX: {X.dtype}')
print(f'Shape of tensorX: {X.size()}')   # Note: tensor.size() is inbuilt function works same as attribute tensor.shape
print(f'Device used for tensorX: {X.device}') 

Datatype of tensorX: torch.float32
Shape of tensorX: torch.Size([3, 4])
Device used for tensorX: cpu
