In [1]:
import torch

### Manipulating Tensors [Tensor Operations]
- Addition
- Subtraction
- Division
- Multiplication


In [8]:
# Create a tensor
tensor = torch.rand(1,3)
tensor

tensor([[0.6171, 0.7164, 0.6063]])

In [15]:
# Tensor Addition
tensor + 10, torch.add(tensor, 10)  # Inbuilt torch function for tensor addition: torch.add(tensor_var, value)

(tensor([[10.6171, 10.7164, 10.6063]]), tensor([[10.6171, 10.7164, 10.6063]]))

In [12]:
# Tensor Subtraction
tensor - 2

tensor([[-1.3829, -1.2836, -1.3937]])

<div style="text-align:center">
  <img src="https://www.mathsisfun.com/algebra/images/matrix-multiply-constant.svg" alt="Matrix Multiplication">
</div>

In [14]:
# Tensor Multiplication
tensor * 10, torch.mul(tensor,10)  # Inbuilt torch function for tensor multiplication: torch.mul(tensor_var, value)

(tensor([[6.1707, 7.1637, 6.0634]]), tensor([[6.1707, 7.1637, 6.0634]]))

## Matrix Multiplication [Dot Product]
<div style="text-align:center">
<img src='https://www.mathsisfun.com/algebra/images/matrix-multiply-a.svg'>
    
    (1, 2, 3) • (7, 9, 11) = 1×7 + 2×9 + 3×11 = 58

<img src='https://www.mathsisfun.com/algebra/images/matrix-multiply-b.svg'>
    
    (1, 2, 3) • (8, 10, 12) = 1×8 + 2×10 + 3×12 = 64

    We can do the same thing for the 2nd row and 1st column:
    (4, 5, 6) • (7, 9, 11) = 4×7 + 5×9 + 6×11 = 139
    And for the 2nd row and 2nd column:
    (4, 5, 6) • (8, 10, 12) = 4×8 + 5×10 + 6×12 = 154
<img src='https://www.mathsisfun.com/algebra/images/matrix-multiply-c.svg'>
</div>

In [39]:
# Matrix Multiplication [Dot Product]
X = torch.tensor([[1, 2, 3], [4, 5, 6]])
Y = torch.tensor([[7, 8], [9, 10], [11, 12]])

print(torch.matmul(X,Y))
print(torch.mm(X,Y))
print(X @ Y)


tensor([[ 58,  64],
        [139, 154]])
tensor([[ 58,  64],
        [139, 154]])
tensor([[ 58,  64],
        [139, 154]])


#### Things to remember before performing matrix multiplication
- The *inner dimension* of the matrix must match:
  - `(3,2) @ (3,2)` won't work
  - `(3,2) @ (2,3)` will work
  - `(2,3) @ (3,2)` will work

- The reulting matrix has shape of *outer dimension*:
  - `(2,3) @ (3,2) = (2,2)`
  - `(3,2) @ (2,3) = (3,3)`

In [40]:
torch.mm(torch.rand(3,2),torch.rand(3,2))

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [46]:
MUL = torch.mm(torch.rand(3,2), torch.rand(2,3))
MUL, MUL.shape

(tensor([[0.2865, 0.3388, 0.3115],
         [0.0709, 0.0953, 0.1143],
         [0.6124, 0.6565, 0.4456]]),
 torch.Size([3, 3]))

In [48]:
# Transpose of a Tensor
tensor1 = torch.rand(2,3)
transpose_tensor = tensor1.T

tensor1, transpose_tensor

(tensor([[0.6676, 0.5804, 0.1635],
         [0.7923, 0.0106, 0.9519]]),
 tensor([[0.6676, 0.7923],
         [0.5804, 0.0106],
         [0.1635, 0.9519]]))

In [56]:
print(f'Shape of original tensor: {tensor1.shape} and\nTransposed tensor: {transpose_tensor.shape}')

Shape of original tensor: torch.Size([2, 3]) and
Transposed tensor: torch.Size([3, 2])


In [60]:
TENSOR = torch.mm(tensor1, transpose_tensor)
TENSOR, TENSOR.shape

(tensor([[0.8093, 0.6908],
         [0.6908, 1.5340]]),
 torch.Size([2, 2]))