In [2]:
import torch

### Manipulating Tensors [Tensor Operations]
- Addition
- Subtraction
- Division
- Multiplication


In [3]:
# Create a tensor
tensor = torch.rand(1,3)
tensor

tensor([[0.1753, 0.9126, 0.7540]])

In [4]:
# Tensor Addition
tensor + 10, torch.add(tensor, 10)  # Inbuilt torch function for tensor addition: torch.add(tensor_var, value)

(tensor([[10.1753, 10.9126, 10.7540]]), tensor([[10.1753, 10.9126, 10.7540]]))

In [5]:
# Tensor Subtraction
tensor - 2

tensor([[-1.8247, -1.0874, -1.2460]])

<div style="text-align:center">
  <img src="https://www.mathsisfun.com/algebra/images/matrix-multiply-constant.svg" alt="Matrix Multiplication">
</div>

In [6]:
# Tensor Multiplication
tensor * 10, torch.mul(tensor,10)  # Inbuilt torch function for tensor multiplication: torch.mul(tensor_var, value)

(tensor([[1.7529, 9.1261, 7.5396]]), tensor([[1.7529, 9.1261, 7.5396]]))

## Matrix Multiplication [Dot Product]
<div style="text-align:center">
<img src='https://www.mathsisfun.com/algebra/images/matrix-multiply-a.svg'>
    
    (1, 2, 3) • (7, 9, 11) = 1×7 + 2×9 + 3×11 = 58

<img src='https://www.mathsisfun.com/algebra/images/matrix-multiply-b.svg'>
    
    (1, 2, 3) • (8, 10, 12) = 1×8 + 2×10 + 3×12 = 64

    We can do the same thing for the 2nd row and 1st column:
    (4, 5, 6) • (7, 9, 11) = 4×7 + 5×9 + 6×11 = 139
    And for the 2nd row and 2nd column:
    (4, 5, 6) • (8, 10, 12) = 4×8 + 5×10 + 6×12 = 154
<img src='https://www.mathsisfun.com/algebra/images/matrix-multiply-c.svg'>
</div>

In [7]:
# Matrix Multiplication [Dot Product]
X = torch.tensor([[1, 2, 3], [4, 5, 6]])
Y = torch.tensor([[7, 8], [9, 10], [11, 12]])

print(torch.matmul(X,Y))
print(torch.mm(X,Y))
print(X @ Y)


tensor([[ 58,  64],
        [139, 154]])
tensor([[ 58,  64],
        [139, 154]])
tensor([[ 58,  64],
        [139, 154]])


#### Things to remember before performing matrix multiplication
- The *inner dimension* of the matrix must match:
  - `(3,2) @ (3,2)` won't work
  - `(3,2) @ (2,3)` will work
  - `(2,3) @ (3,2)` will work

- The reulting matrix has shape of *outer dimension*:
  - `(2,3) @ (3,2) = (2,2)`
  - `(3,2) @ (2,3) = (3,3)`

In [8]:
torch.mm(torch.rand(3,2),torch.rand(3,2))

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [9]:
MUL = torch.mm(torch.rand(3,2), torch.rand(2,3))
MUL, MUL.shape

(tensor([[0.5195, 0.4155, 0.5635],
         [0.0855, 0.0761, 0.1172],
         [0.3807, 0.3451, 0.5426]]),
 torch.Size([3, 3]))

In [10]:
# Transpose of a Tensor
tensor1 = torch.rand(2,3)
transpose_tensor = tensor1.T

tensor1, transpose_tensor

(tensor([[0.6834, 0.1668, 0.9824],
         [0.2398, 0.7747, 0.0414]]),
 tensor([[0.6834, 0.2398],
         [0.1668, 0.7747],
         [0.9824, 0.0414]]))

In [11]:
print(f'Shape of original tensor: {tensor1.shape} and\nTransposed tensor: {transpose_tensor.shape}')

Shape of original tensor: torch.Size([2, 3]) and
Transposed tensor: torch.Size([3, 2])


In [12]:
TENSOR = torch.mm(tensor1, transpose_tensor)
TENSOR, TENSOR.shape

(tensor([[1.4599, 0.3338],
         [0.3338, 0.6594]]),
 torch.Size([2, 2]))

### Tensor Aggregation
Find min, max, mean, sum, ... 

In [16]:
# Create a Tensor
x = torch.arange(0, 10)
x, x.dtype

(tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.int64)

In [14]:
# Find min and max
torch.max(x), torch.min(x)

(tensor(9), tensor(0))

In [15]:
torch.mean(x)

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

#### Note: 
- We just faced a common error in Tensor DataTypes
    - *Meaning, `torch.mean()` only accepts float values*

In [22]:
# Changing tensor from int64[long] to float32
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(4.5000), tensor(4.5000))

In [21]:
torch.sum(x)

tensor(45)

Find positonal min & max

In [38]:
x = torch.arange(2, 20, 5)    # (start, end=, step)
x

tensor([ 2,  7, 12, 17])

In [39]:
# Returns positon in tensor that has minimum value with argmin() & maximum value with argmax()
x.argmin(), x.argmax()

(tensor(0), tensor(3))

In [41]:
x[0], x[3]

(tensor(2), tensor(17))