In [2]:
import torch

## Reshaping, Viewing, Stacking, Squeezing, Unsqueezing & Permute Tensors

1. **Reshaping**: Reshapes an input tensor to a defined shape.
2. **View**: Returns a view of the input tensor of certain shape but keep the same memory as original .
3. **Stacking**: Combine multiple tenmsors on top of each other <a href='https://pytorch.org/docs/stable/generated/torch.vstack.html'>(TORCH.VSTACK)</a> or side by side <a href='https://pytorch.org/docs/stable/generated/torch.hstack.html'>(TORCH.HSTACK)</a>.
4. **Squeeze**: Removes all `1` dimensions from a tensor.
5. **Unsqueeze**: Add `1` dimension to a target tensor.
6. **Permute**: Return a view of the input with dimensions permuted(swapped) in a certain way.

### Reshape

In [3]:
x = torch.arange(1.,10.)
x, x.shape, x.ndim

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]), 1)

In [4]:
# Adding extra dimensions
x_reshaped = x.reshape(1, 5)
x_reshaped, x_reshaped.shape

RuntimeError: shape '[1, 5]' is invalid for input of size 9

#### `torch.reshape()` is only compatible when the torch size matches as:
- `x = torch.arange(1.,10.)`</br>
    `x, x.shape`
    ```bash
    (tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))
    ```
-   `torch.Size([9]) = torch.reshape(1, 9)`
    
    *1x9 = 9, 3x3 = 9*
    
-   `x_reshaped = x.reshape(1, 9)`
    ```bash
    (tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))
    ```



In [5]:
# Adding extra dimensions
x_reshaped = x.reshape(3, 3)
y_reshaped = x.reshape(9, 1)

x_reshaped, x_reshaped.shape, x_reshaped.ndim

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]),
 2)

In [6]:
y_reshaped, y_reshaped.shape, y_reshaped.ndim

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]),
 2)

### View

In [7]:
# Change the view
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [8]:
# Changing z, changes x
# this is because a view of a tensor shares the same memory as the original tensor
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

### Stack
<a href='https://pytorch.org/docs/stable/generated/torch.stack.html'>TORCH.STACK Documentation</a>    

In [9]:
# Concatenates a sequence of tensors along a new dimension.
x = torch.stack([x, x, x, x], dim=0)
x

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

### Squeeze
<a href='https://pytorch.org/docs/stable/generated/torch.squeeze.html'>TORCH.SQUEEZE Documentation</a> 

In [12]:
x = torch.rand(1,2,2)
print(x, x.size())

y = torch.squeeze(x)
print(y, y.size())

y = torch.squeeze(x, 0)
print(y, y.size())

y = torch.squeeze(x, 1)
print(y, y.size())

tensor([[[0.5099, 0.2453],
         [0.1440, 0.2323]]]) torch.Size([1, 2, 2])
tensor([[0.5099, 0.2453],
        [0.1440, 0.2323]]) torch.Size([2, 2])
tensor([[0.5099, 0.2453],
        [0.1440, 0.2323]]) torch.Size([2, 2])
tensor([[[0.5099, 0.2453],
         [0.1440, 0.2323]]]) torch.Size([1, 2, 2])


In [16]:
y = torch.squeeze(x, (2, 1))
y

tensor([[[0.5099, 0.2453],
         [0.1440, 0.2323]]])

In [17]:
# Squeezing y_reshaped tensor
y_reshaped, y_reshaped.size()

(tensor([[5.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [18]:
# torch.squeeze() removes all single dimensions from a target tensor
y_reshaped.squeeze(), y_reshaped.squeeze().shape

(tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [19]:
print(f'Previous tensor: \n{y_reshaped}\nPrevious Shape: {y_reshaped.shape}')
print('-'*60)
print(f'New tensor: \n{y_reshaped.squeeze()}\nNew Shape: {y_reshaped.squeeze().shape}')

Previous tensor: 
tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
Previous Shape: torch.Size([9, 1])
------------------------------------------------------------
New tensor: 
tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New Shape: torch.Size([9])


### Unsqueeze
<a href='https://pytorch.org/docs/stable/generated/torch.unsqueeze.html'>TORCH.UNSQUEEZE Documentation</a> 

In [20]:
# torch.unsqueeze() adds a single dimension to a target tensot at a specific dimension (dim)
y_squeeze = y_reshaped.squeeze()
print(f'Previous tensor: \n{y_squeeze}\nPrevious Shape: {y_squeeze.shape}')
print('-'*60)


y_unsqueezed = y_squeeze.unsqueeze(dim=0)
print(f'For dim 0 , New tensor: \n{y_unsqueezed}\nNew Shape: {y_unsqueezed.shape}')
print('-'*60)

y_unsqueezed = y_squeeze.unsqueeze(dim=1)
print(f'For dim 1, New tensor: \n{y_unsqueezed}\nNew Shape: {y_unsqueezed.shape}')


Previous tensor: 
tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous Shape: torch.Size([9])
------------------------------------------------------------
For dim 0 , New tensor: 
tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New Shape: torch.Size([1, 9])
------------------------------------------------------------
For dim 1, New tensor: 
tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
New Shape: torch.Size([9, 1])


### Permute
<a href='https://pytorch.org/docs/stable/generated/torch.permute.html'>TORCH.PERMUTE Documentation</a> 


In [21]:
# torch.permute rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(223,224,3)     # (height, width, color-channels)-----axis:(0, 1, 2)

# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1)    # (color-channels, height, width)-----axis:(2, 0, 1)

print(f'Shape of original tensor: {x_original.shape}')
print(f'Shape of permuted tensor: {x_permuted.shape}')

Shape of original tensor: torch.Size([223, 224, 3])
Shape of permuted tensor: torch.Size([3, 223, 224])


In [22]:
x_original[0, 0, 0], x_permuted[0, 0, 0]

(tensor(0.8070), tensor(0.8070))

In [23]:
x_original[0, 0, 0] = 727
x_original[0, 0, 0], x_permuted[0, 0, 0]

(tensor(727.), tensor(727.))