<a href="https://colab.research.google.com/github/LuluW8071/Data-Science/blob/main/Pytorch/06_Pytorch_Fundamentals_Exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## [Exercises](https://www.learnpytorch.io/00_pytorch_fundamentals/#exercises)
- Documentation reading - [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor) and for [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics)

In [17]:
import torch



- Create a random tensor with shape `(7, 7)`

In [20]:
x = torch.rand(7, 7)
x.shape

torch.Size([7, 7])

- Perform a matrix multiplication on the tensor from shape `(7, 7)` with another random tensor with shape `(1, 7)` </br> (hint: you may have to transpose the second tensor)

In [25]:
y = torch.rand(1,7).T

mul = torch.matmul(x,y)
mul, mul.shape

(tensor([[2.7400],
         [2.5953],
         [1.7910],
         [2.0822],
         [1.5014],
         [2.9131],
         [3.0145]]),
 torch.Size([7, 1]))

- Set the random seed to `0` and do exercises of matrix multiplication over again

In [29]:
torch.manual_seed(0)
tensor_x = torch.rand(5,2)
torch.manual_seed(0)
tensor_y = torch.rand(5,2)
tensor_y_transpose = tensor_y.T

x_mul_y = torch.matmul(tensor_x, tensor_y_transpose)
x_mul_y, x_mul_y.shape, tensor_x == tensor_y

(tensor([[0.8364, 0.1453, 0.6397, 0.9319, 0.7119],
         [0.1453, 0.0253, 0.1109, 0.1617, 0.1238],
         [0.6397, 0.1109, 0.4966, 0.7191, 0.5410],
         [0.9319, 0.1617, 0.7191, 1.0438, 0.7901],
         [0.7119, 0.1238, 0.5410, 0.7901, 0.6074]]),
 torch.Size([5, 5]),
 tensor([[True, True],
         [True, True],
         [True, True],
         [True, True],
         [True, True]]))