## [Exercises](https://www.learnpytorch.io/00_pytorch_fundamentals/#exercises)
- Documentation reading - [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor) and for [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics)

In [27]:
import torch



- Create a random tensor with shape `(7, 7)`

In [28]:
x = torch.rand(7, 7)
x.shape

torch.Size([7, 7])

- Perform a matrix multiplication on the tensor from shape `(7, 7)` with another random tensor with shape `(1, 7)` </br> (hint: you may have to transpose the second tensor)

In [29]:
y = torch.rand(1,7).T

mul = torch.matmul(x,y)
mul, mul.shape

(tensor([[1.6711],
         [1.2399],
         [2.0411],
         [1.2607],
         [1.7647],
         [1.2399],
         [1.6091]]),
 torch.Size([7, 1]))

- Set the random seed to `0` and do exercises of matrix multiplication over again

In [30]:
torch.manual_seed(0)
tensor_x = torch.rand(5,2)
torch.manual_seed(0)
tensor_y = torch.rand(5,2)
tensor_y_transpose = tensor_y.T

x_mul_y = torch.matmul(tensor_x, tensor_y_transpose)
x_mul_y, x_mul_y.shape, tensor_x == tensor_y

(tensor([[0.8364, 0.1453, 0.6397, 0.9319, 0.7119],
         [0.1453, 0.0253, 0.1109, 0.1617, 0.1238],
         [0.6397, 0.1109, 0.4966, 0.7191, 0.5410],
         [0.9319, 0.1617, 0.7191, 1.0438, 0.7901],
         [0.7119, 0.1238, 0.5410, 0.7901, 0.6074]]),
 torch.Size([5, 5]),
 tensor([[True, True],
         [True, True],
         [True, True],
         [True, True],
         [True, True]]))

- Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one). If there is, set the GPU random seed to `1234`.

- Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed).

In [31]:
# manual_seed for cpu
torch.manual_seed(1234)
tensor_x = torch.rand(2, 3)

# manual_seed for cuda
torch.cuda.manual_seed(1234)
tensor_y = torch.rand(2, 3).to('cuda')

torch.cuda.manual_seed(1234)
tensor_z = torch.rand(2, 3).to('cuda')

tensor_x, tensor_x.device, tensor_y, tensor_z

(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]]),
 device(type='cpu'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'),
 tensor([[0.7749, 0.8208, 0.2793],
         [0.6817, 0.2837, 0.6567]], device='cuda:0'))

- Perform a matrix multiplication on the tensors you created above (again, you may have to adjust the shapes of one of the tensors).

In [33]:
tensor_z_transpose = tensor_z.T

mul = torch.matmul(tensor_y, tensor_z_transpose)
mul, mul.shape

(tensor([[0.6126, 0.6106],
         [1.0574, 0.8181]], device='cuda:0'),
 torch.Size([2, 2]))

- Find the maximum and minimum values of the output of above.

In [35]:
mul.max(), mul.min()

(tensor(1.0574, device='cuda:0'), tensor(0.6106, device='cuda:0'))

- Find the maximum and minimum index values

In [45]:
mul.argmax(), mul.argmin()

(tensor(2, device='cuda:0'), tensor(1, device='cuda:0'))

- Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape `(10)`. Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

In [55]:
# Set the seed
torch.manual_seed(7)
rand_tensor = torch.rand(1, 1, 1, 10)

rand_tensor, rand_tensor.shape

(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 torch.Size([1, 1, 1, 10]))

In [57]:
# squeezing
rand_squeeze = rand_tensor.squeeze()
rand_squeeze, rand_squeeze.shape

(tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]),
 torch.Size([10]))

In [58]:
rand_squeeze[0], rand_squeeze[0].shape

(tensor(0.5349), torch.Size([]))

In [59]:
rand_squeeze[1], rand_squeeze[1].shape

(tensor(0.1988), torch.Size([]))