## Running tensors & Pytorch objects on the GPUs

### 1. Getting GPU
GPUs is used for faster computation on numbers thanks to CUDA + Nvidia hardware
- Google Collab: Free [12hrs Runtime limit]
- Own Device: [Investment, [CUDA Installation](https://developer.nvidia.com/cuda-toolkit)]
- [Cloud Computing](https://pytorch.org/get-started/cloud-partners/): GCP, AWS, Azure(Microsoft) [Renting, Investment,  [CUDA Installation](https://developer.nvidia.com/cuda-toolkit)]


In [3]:
!nvidia-smi

Sat Jan  6 12:10:04 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   42C    P8               9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

### 2. Checking for GPU access with PyTorch

In [5]:
import torch

print(torch.__version__)
print(torch.cuda.is_available())

2.1.0+cu121
True


In [9]:
# Setup device agnostic code
device = 'cuda' if torch.cuda.is_available() else 'cpu'

device, torch.cuda.device_count()

('cuda', 1)

For python scripts (.py) file, [Device Agnostic Code](https://pytorch.org/docs/stable/notes/cuda.html#device-agnostic-code) can be used

### 3. Putting tensors (and models) on the GPU

In [10]:
# Create a tensor(default is on cpu)
tensor = torch.tensor([1, 2, 3])

tensor, tensor.device

(tensor([1, 2, 3]), device(type='cpu'))

In [11]:
# Move tensor to GPU if available
tensor_gpu = tensor.to(device)
tensor_gpu

tensor([1, 2, 3], device='cuda:0')

### 4. Moving tensors back to CPU

In [12]:
# If tensor is on GPU, can't transform it to numpy
tensor_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [14]:
# To fix the GPU tensor with NumPy issue, we can first set it back to the cpu
tensor_back_on_cpu = tensor_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])