In [12]:
import torch
import numpy as np

### Indexing
Selecting data form 
[Similar as numpy indexing]

In [13]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.size()

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [2]:
# Indexing on dim=2, dim=1, dim=0
x[0], x[0, 0], x[0, 0, 0]   # x[0,0] = x[0][0]

(tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 tensor([1, 2, 3]),
 tensor(1))

In [3]:
x[1, 1, 1]    # Returns error as torch.Size([1, 3, 3])) meaning indexing at dim=2 equals 0 only

IndexError: index 1 is out of bounds for dimension 0 with size 1

In [4]:
x[0, 1, 1], x[0, 2, 2]

(tensor(5), tensor(9))

In [5]:
# ':' can also be used to select all of a traget dimension
x[:, 0]

tensor([[1, 2, 3]])

In [6]:
# Get all values of 0th and 1st dimenstion but only index[1] of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [11]:
# Get all values of 0th dim but only the index[1] of 1st and 2nd dim
# Get index 0 of 0th and 1st dim and all values of 2nd dim
x[:, 1, 1], x[0, 0, :]

(tensor([5]), tensor([1, 2, 3]))

In [10]:
# Index on x to return 9
# Index on x to return [3, 6, 9]
x[:, 2, 2], x[:, : ,2]

(tensor([9]), tensor([[3, 6, 9]]))

## Pytorch Tensors & Numpy
Numpy is a popular scientific Python numerical computing library
And because of this, Pytorch has functionality to interact with it
* Data in Numpy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> `ndarray.numpy()`

In [23]:
array = np.arange(1.0, 7.0)
tensor = torch.from_numpy(array)    
# When converting from numpy->pytorch,
# pytorch reflects numpy default dtype of 'float 64' unless specified otherwise 
array, tensor

(array([1., 2., 3., 4., 5., 6.]),
 tensor([1., 2., 3., 4., 5., 6.], dtype=torch.float64))

In [24]:
torch.arange(1.0, 7.0).dtype, tensor.dtype

(torch.float32, torch.float64)

In [25]:
# Change the value of array
array = array + 1
array, tensor   # doesnt change the value of tensor

(array([2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6.], dtype=torch.float64))

In [29]:
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()

tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [31]:
# Change the tensor, waht happens to 'numpy_tensor'?
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibilty
[PYTORCH.REPRODUCIBILITY](https://pytorch.org/docs/stable/notes/randomness.html)

[Trying to take random out of random]</br>
In short how a Neural Network(NN) learns:
- `Start with random numbers`
- `Tensor Operations`
- `Update random numbers to try and make them better representation of data`
- `Repeat again & again & again...`

In [35]:
# Everytime you run torch.rand() it gives random tensors
torch.rand(3, 3)

tensor([[0.1569, 0.8118, 0.6555],
        [0.8915, 0.9502, 0.0394],
        [0.1655, 0.9609, 0.0930]])

To reduce the randomness in NN and PyTorch comes the concept of **random seed**
Essentially, what the random seed does is 'flavor' the randomness

In [52]:
# Create two random tensors
random_tensor_A = torch.rand(3, 3)
random_tensor_B = torch.rand(3, 3)

random_tensor_A, random_tensor_B, random_tensor_A == random_tensor_B

(tensor([[0.3882, 0.5129, 0.7525],
         [0.8239, 0.3759, 0.9386],
         [0.6016, 0.7592, 0.8250]]),
 tensor([[0.4374, 0.5726, 0.4467],
         [0.2867, 0.3382, 0.3489],
         [0.3974, 0.3013, 0.7213]]),
 tensor([[False, False, False],
         [False, False, False],
         [False, False, False]]))

In [58]:
# Create two random tensor but reproducible tensors
torch.manual_seed(42)
random_tensor_C = torch.rand(3, 3)

# Note: torch.manual_seed() works for only 1 block of torch.rand()
torch.manual_seed(42)
random_tensor_D = torch.rand(3, 3)

random_tensor_C, random_tensor_D, random_tensor_C == random_tensor_D

(tensor([[0.8823, 0.9150, 0.3829],
         [0.9593, 0.3904, 0.6009],
         [0.2566, 0.7936, 0.9408]]),
 tensor([[0.8823, 0.9150, 0.3829],
         [0.9593, 0.3904, 0.6009],
         [0.2566, 0.7936, 0.9408]]),
 tensor([[True, True, True],
         [True, True, True],
         [True, True, True]]))